# Generated by Django 5.1.1 on 2024-10-12 17:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store_app', '0008_remove_order_additional_info'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderitem',
            name='order',
        ),
        migrations.DeleteModel(
            name='Order',
        ),
        migrations.DeleteModel(
            name='OrderItem',
        ),
    ]
